correct shell error mgmt

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 BUILD_DIR=$1
 CACHE_DIR=$2
-set -o # fail fast
+set -e # fail fast
+set -o pipefail
 
 echo "-----> Starting perl buildpack"
 
diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -2,7 +2,8 @@
 # bin/detect <build-dir>
 BUILD_DIR=$1
 
-set -o # fail fast
+set -e # fail fast
+set -o pipefail
 
 if [ -f "${BUILD_DIR}/cpanfile" ]; then
   echo ccperl
